[WIP]: Add Osmo CTA Section
osmosis-labs/osmosis-website pull request #20
Opened 2024-03-20 17:22 UTC by fabryscript

2024-03-23 21:35 UTC, DavideSegullo requested changes

2024-03-23 21:35 UTC, DavideSegullo commented on components/sections/osmo-cta/backers-section.tsx
> +  const [isExpanded, setIsExpanded] = useState(false);
If let the button behave like a checkbox, we can remove this react state and use "has" selector:
https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-descendants

So we can create an expandable list without any react state

2024-03-23 21:35 UTC, DavideSegullo commented on public/assets/bg-osmo-cta-2xl.svg
Why do we need so many svgs? they're all pretty similar, can we just export the left image and then use absolute position?

2024-03-24 00:15 UTC, fabryscript commented on public/assets/bg-osmo-cta-2xl.svg
referenced in #31

2024-03-24 20:25 UTC, merged